//Given an array arr[] of N positive elements. The task is to find the 
//Maximum AND Value generated by any pair of element from the array

#include <iostream>
using namespace std;

int checkbit(int pattern, int arr [], int n)
{
    int count = 0;
    for (int i=0;i<n;i++)
    {
        if ((pattern&arr[i])==pattern) count++;
    }
    return count;
}

int maxAND (int arr[], int n)
{
    int result = 0,count;
    for (int bit=31;bit>=0;bit--)
    {
        count = checkbit((result | (1<<bit)),arr,n);
        if (count>1) result = result | (1<<bit);
    }
    return result;
}

int main()
{
    int t;
    cin>>t;
    while(t--)
    {
        int n;
        cin>>n;
        int arr[n];
        for(int i=0;i<n;i++) cin>>arr[i];
        cout<<maxAND(arr,n)<<"\n";
    }
    return 0;
}
